; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:uno]
platform = atmelavr
board = uno
framework = arduino
lib_extra_dirs = 
    ~/Documents/Arduino/libraries
lib_deps =
    milesburton/DallasTemperature @ ^3.11.0
    paulstoffregen/OneWire @ ^2.3.8
    olikraus/U8g2 @ ^2.36.0
    https://github.com/jarzebski/Arduino-DS3231.git
    jandrassy/WiFiEspAT @ ^1.4.6
    arduino-libraries/ArduinoHttpClient @ ^0.6.1
    boseji/ArduinoBase64 @ ^1.1.1

[env:d1_mini]
platform = espressif8266
board = d1_mini
board_build.mcu = esp8266
framework = arduino
monitor_speed = 115200
lib_extra_dirs = 
    ~/Documents/Arduino/libraries
lib_deps =
    milesburton/DallasTemperature @ ^3.11.0
    paulstoffregen/OneWire @ ^2.3.8
    olikraus/U8g2 @ ^2.36.0
    https://github.com/jarzebski/Arduino-DS3231.git    

[env:esp01_1m]
platform = espressif8266
board = esp01_1m
framework = arduino
monitor_speed = 115200
lib_extra_dirs = 
    ~/Documents/Arduino/libraries
lib_deps =
    milesburton/DallasTemperature @ ^3.11.0
    paulstoffregen/OneWire @ ^2.3.8
    olikraus/U8g2 @ ^2.36.0
    https://github.com/jarzebski/Arduino-DS3231.git
